CREATE TABLE items (
  item_id UUID NOT NULL,
  type VARCHAR,
  citation_key VARCHAR,
  language VARCHAR,
  accessed DATE,
  available_date DATE,
  event_date DATE,
  issued DATE,
  original_date DATE,
  submitted DATE,
  abstract VARCHAR,
  annote VARCHAR,
  archive VARCHAR,
  archive_collection VARCHAR,
  archive_location VARCHAR,
  archive_place VARCHAR,
  authority VARCHAR,
  call_number VARCHAR,
  chapter_number VARCHAR,
  citation_number VARCHAR,
  citation_label VARCHAR,
  collection_number VARCHAR,
  collection_title VARCHAR,
  container_title VARCHAR,
  container_title_short VARCHAR,
  dimensions VARCHAR,
  division VARCHAR,
  doi VARCHAR,
  edition VARCHAR,
  event_title VARCHAR,
  event_place VARCHAR,
  first_reference_note_number VARCHAR,
  genre VARCHAR,
  isbn VARCHAR,
  issn VARCHAR,
  issue VARCHAR,
  jurisdiction VARCHAR,
  keyword VARCHAR,
  locator VARCHAR,
  medium VARCHAR,
  note VARCHAR,
  number VARCHAR,
  number_of_pages VARCHAR,
  number_of_volumes VARCHAR,
  original_publisher VARCHAR,
  original_publisher_place VARCHAR,
  original_title VARCHAR,
  page VARCHAR,
  page_first VARCHAR,
  part VARCHAR,
  part_title VARCHAR,
  pmcid VARCHAR,
  pmid VARCHAR,
  printing VARCHAR,
  publisher VARCHAR,
  publisher_place VARCHAR,
  refers VARCHAR,
  reviewed_genre VARCHAR,
  reviewed_title VARCHAR,
  scale VARCHAR,
  section VARCHAR,
  source VARCHAR,
  status VARCHAR,
  supplement VARCHAR,
  title VARCHAR,
  title_short VARCHAR,
  url VARCHAR,
  version VARCHAR,
  volume VARCHAR,
  volume_title VARCHAR,
  volume_title_short VARCHAR,
  year_suffix VARCHAR,
  revision INTEGER NOT NULL,
  stage INTEGER NOT NULL,
  created TIMESTAMP DEFAULT current_timestamp NOT NULL,
  PRIMARY KEY (item_id, revision),
  CHECK (stage IN (0, -1)),
  CHECK (revision >= 1)
);
