CREATE TABLE person_roles (
  person_role_id UUID NOT NULL,
  person_id UUID,
  position VARCHAR,
  superorganization VARCHAR,
  organization VARCHAR,
  suborganization VARCHAR,
  division VARCHAR,
  subdivision VARCHAR,
  address VARCHAR,
  city VARCHAR,
  region VARCHAR,
  country VARCHAR,
  start_year INTEGER,
  end_year INTEGER,
  start_month INTEGER,
  end_month INTEGER,
  start_day INTEGER,
  end_day INTEGER,
  order_priority INTEGER,
  revision INTEGER NOT NULL,
  stage INTEGER NOT NULL,
  created TIMESTAMP DEFAULT current_timestamp NOT NULL,
  PRIMARY KEY (person_role_id, revision),
  CHECK (stage IN (0, -1)),
  CHECK (revision >= 1)
);
